name: Tests - currently a NOOP since there are no tests

on:
  [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Pass
        run: |
          echo "it works"

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: test
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
